# SConscript
#
# Copyright (c) 2015 Kevin Laeufer <kevin.laeufer@rwth-aachen.de>
#
# This file is part of Ostfriesentee.
#
# Ostfriesentee is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Ostfriesentee is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Ostfriesentee.  If not, see <http://www.gnu.org/licenses/>.

import os

Import('env')

base_lib = SConscript(['../../ostfriesentee/lib/base/SConscript'], exports = 'env')
ostfriesentee_lib = SConscript(['../../ostfriesentee/lib/ostfriesentee/SConscript'], exports = 'env')


app = env.OstfriesenteeApplication('enums', ['java'], OFT_LIBS=['base', 'ostfriesentee'])

Return('app')
